# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70ee0b1669299624832e4eceb0033145c3895e57f61965635889cc3c63402ff5397f820e3338c62805d9c4fe4d55f8373aa237b31dcf5c2ef587b0c3b08aff7e
  backend_url: "http://localhost:3002"
  api_path: "api/v1"

test:
  secret_key_base: 1e41b4bae4184fa14261682830ec7836405b802ebf8869f5fa3676b7f99fcfa926859dc7b43627e9f53466608858d0a144522603a7adeba03fd3fc035175e83c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 1e41b4bae4184fa14261682830ec7836405b802ebf8869f5fa3676b7f99fcfa926859dc7b43627e9f53466608858d0a144522603a7adeba03fd3fc035175e83c
  backend_url: "https://boiling-meadow-32308.herokuapp.com"
  api_path: "api/v1"
